### PR TITLE
Add EveryPay linkpay feature

### LINKED ISSUE #606: Payment link to auction winning, payment reminder and overdue email messages
Add a PSD2 payment links to auction winning, invoice payment reminder and overdue/violation email notifications

https://support.every-pay.com/et/merchant-support/linkpay-makselink/
https://support.every-pay.com/et/search/linkpay/

### PR DESCRIPTION
**Pull request by yulgolem**
Closes #606

### CODE REVIEW

**Comment by yulgolem** [comment]
Callback URL must be set in e-shop settings of merchant portal
image

Variables to be set in `customization.yml` are:
```
payment_methods:
  every_pay:
    linkpay_prefix: 'https://igw-demo.every-pay.com/lp'
    linkpay_check_prefix: 'https://igw-demo.every-pay.com/api/v3/payments/'
    linkpay_token: 'rucd4v'
```

**Review by OlegPhenomenon — APPROVED** [review]

**Comment by yulgolem** [comment]
We need to add invoice ID and domain name to the linkpay form

**Comment by yulgolem** [comment]
New fields must be added to link via link edit e.g. https://mwt-demo.every-pay.com/linkpay/links/104950 , then enabled on a template.

**Comment by vohmar** [comment]
this is the payment description example: https://internet.ee/EE, st570623, 114 - instead of internet.ee, could we add there auction.internet.ee and invoice nr instead of stan and order reference so it would be more meaningful

also the transaction id 114 - could this be replaces with something more difficult to guess - in case of regular card payments (not the linkpay) the example of this id would be 4db008dcfa30d4769f8689815855e5. Not sure if there is a security concern here.

**Comment by yulgolem** [comment]
114 here is an order reference, it equals payment order id atm and it's needed to mark payment order as paid, but it can be changed to uuid like `f485aad3-efdd-4d4e-829d-e7b7713f1ca1`.
And actually have no idea about payment description - what is it, where can I find it? We do not have such a field in form.

image

**Pull request merged**
