### PR TITLE
Add disclaimer to offers form

### LINKED ISSUE #283: Remind users that they are making a bid in auction
It seems that some users tend to not notice that they are bidding in an auction and seem to think that minimum bid sum indicates the bid that would be the highest at that moment. To  address this add notification to the "submit offer" view (ie: /auctions/62d93ec1-94d5-4e49-a618-1bc51dea8c3f/offers/new)

et: NB: tegemist on pimeoksjoniga! Domeeninimele võib olla teisigi huvilisi. Tee pakkumine mida pärast kahetsema ei pea. Teiste pakkumiste kohta info puudumine ei tähenda, et neid pole!

en: NB: this is blind auction! This domain name might have others that are also interested in it. Make a bid that you will not regret later. No information about other bids does not mean there are not any!

### PR DESCRIPTION
**Pull request by maciej-szlosarczyk**
Fixes #283

### CODE REVIEW

**Comment by maciej-szlosarczyk** [comment]
Screenshot 2019-06-10 at 11 57 33

**Comment by vohmar** [comment]
Please put the text above pakkumus field (below the orange bar) with small changes to the text:

et: Tegemist on pimeoksjoniga ning domeeninimele võib olla teisigi huvilisi. Teiste pakkumiste kohta info puudumine ei tähenda, et neid pole. Tee pakkumine vastavalt oma hinnangule domeeni väärtuse kohta.

en: This is blind auction and the domain name might have others interested in it as well. No information about other bids does not mean there are not any. Make a bid according to the value of the domain name to you.

**Comment by maciej-szlosarczyk** [comment]
The text and positioning are now updated.

**Comment by vohmar** [comment]
* Positioning is good
* Please make one more change to the text

et: Tegemist on pimeoksjoniga, kus pakkumised ei ole nähtavad. Domeeninimele võib olla ka teisi pakkujaid. Tee pakkumine vastavalt oma hinnangule domeeninime väärtuse kohta.

en: This is a blind auction where bids are not public. There might be other bids. Make an offer according to the value the domain name holds to you.

**Pull request merged**
